logfilename log\ai_pyramid_options.log
logfileon
;__________
vpoint
-1,-1,1
;3d>ai_pyramid>p1>p2>p3>p4>apex
(defun c:checkent() (if (= (entget (Car (entsel))) nil) (alert "ErR")))
;________1
ai_pyramid
0,0,0
1,0
1,1
0,1
0.5,.5,1
checkent
0,0,0
;________2
ai_pyramid
3,0,0
5,0
3,1
t
1,1,-1
checkent
3,0,0
;________3
ai_pyramid
6,0,0
.x
1
.y
3
.z
4
2,1,-1
1,2,-3
r
2,1,0
1,2,0
checkent
6,0,0
;________4
ai_pyramid
0,3,0
1,3,0
1,4,0
0,4
t
0,3,-1
1,3,-1
1,4,-1
0,4,-1
checkent
0,3,0
;________5
ai_pyramid
3,3,0
4,3
3,4
3,4
t
4,3,1
5,3,1
5,4,1
4,4,1
checkent
3,3,0
;________6
ai_pyramid
3,3,0
2,1
1,2
t
t
3,3,1
2,1,1
1,2,1
checkent
3,3,0
;________
dxfout output_dxf\ai_pyramid_options.dxf
6
quit
y
