logfilename log\break_options.log
logfileon
;________
(defun c:checkbreak() (setq en nil) (setq en (entget (Car (entsel)))) (if (/= en nil) (alert "break did not work correctly")))
;________1
line
0,0
3,0

;________
zoom
extents
;________
break
1.4,0
1.6,0
;________
checkbreak
1.5,0
;________
erase
all

;________2
circle
1,1
1
;________
zoom
extents
;________
break
2,1
0,1
;________
checkbreak
1,2
;________
erase
all

;________3
line
0,0
3,0

;________
zoom
extents
;________
break
2,0
f
1.4,0
1.6,0
;________
checkbreak
1.5,0
;________
erase
all

;________4
circle
1,1
1
;________
zoom
extents
;________
break
2,1
f
0,1
2,1
;________
checkbreak
1,0
;________
erase
all

;________5
pline
1,1
3,1
3,2
1,2
c
;________
zoom
extents
;________
break
2,1
1.8,1
;________
checkbreak
1.9,1
;________
erase
all

;________6
ellipse
1,1
3,1
2,1.5
;________
zoom
extents
;________
break
2,0.5
2,1.5
;________
checkbreak
3,1
;_________
dxfout output_dxf\break_options.dxf
6
quit
y
