logfilename log\change_options.log
logfileon
;_________
(defun c:checkchange() (setq en nil) (setq en (entget (Car (entsel)))) (if (= en nil) (alert "chage did not work correctly")))
;_________1
line
1,1
2,2

;_________
change
l

3,2
;_________
checkchange
3,2
;_________
erase
all

;_________2
circle
1,1
2,2
;_________
change
l

3,2
;_________
checkchange
3,2
;_________
erase
all

;_________3
ray
1,1
2,2

;_________
change
l

3,2
;_________
checkchange
3,2
;_________
erase
all

;_________4
xline
1,1
2,2

;_________
change
l

3,2
;_________
checkchange
3,2
;_________
erase
all

;_________5
text
1,1


OOOOO
;_________
change
l

3,2




;_________
checkchange
3,2
;_________
erase
all

;_________6
-style
st1
arial





;_________
text
1,1
.2
20
OOOOO
;_________
change
l

3,2
st1
.5
45
OoOoO
;_________
checkchange
3,2
;_________
erase
all

;_________7
attdef

Oname
Oprompt
Otext
1,1
.2
20
;_________
change
l

3,2
st1
.5
45
OoOoO
oOoOo
OoOoO
;_________
checkchange
3,2
;_________
erase
all

;_________8
line
1,1
2,1

block
abc
1,1
all

;_________
insert
abc
1,1



;_________
change
l

3,2
45
;_________
checkchange
3,2
;_________
erase
all

;_________10
-layer
n
la1

;_________
vpoint
1,1,1
;_________
solid
0,0
1,0
1,1
0,1

;_________
change
l

p
c
cyan
e
-1
la
la1
lt
continuous
s
10
lw
15
t
1

erase
all

;_________9____________
ray
1,1
2,2

;_________
change
l

e


;_________
change
l

e
d
3,2
;_________
change
l

e
a
4,3
;_________
checkchange
3,2
;_________
erase
all

;__________
dxfout output_dxf\change_options.dxf
6
quit
y
