;_This_script_depends_on_78551_for_ACIS_Builds
logfilename log\edgesurf_options.log
logfileon
;_________
(defun c:chk()(if (/= (cdr (assoc 0 (entget (entlast)))) "POLYLINE") (alert "Err! Ignore if this is ACIS build")) )
surftab1
20
surftab2
20
peditaccept
0
;__line__
line
0,0
1,0
1,1
0,1
c
;________
zoom
extents
;________
edgesurf
.5,0
1,.5
.5,1
0,.5
;________
chk
;________
move
all

0,0
1,0
;________
rectangle
0,0
1,1
;________
explode
l
;________
zoom
extents
;________
edgesurf
.5,0
1,.5
.5,1
0,.5
;________
chk
;__pline__
move
all

0,0
0,1
;________
pline
0,0
1,0



1,1



0,1



0,0

;________
zoom
extents
;________
edgesurf
.5,0
1,.5
.5,1
0,.5
;________
chk
;__arc__
move
all

0,0
1,0
;________
arc
c
0.5,0.5
0,0
1,0
arc
c
0.5,0.5
1,0
1,1
arc
c
0.5,0.5
1,1
0,1
arc
c
0.5,0.5
0,1
0,0
;________
zoom
extents
;________
edgesurf
.5,-.2071
1.2071,.5
.5,1.2071
-0.2071,.5
;________
chk
;__spline__
move
all

0,0
0,1
;________
pline
0,0
.5,-.2071
1,0

pedit
l
f

pline

1.2071,.5
1,1

pedit
l
f

pline

.5,1.2071
0,1

pedit
l
f

pline

-0.2071,.5
0,0

pedit
l
f

;________
zoom
extents
;________
edgesurf
.5,-.2071
1.2071,.5
.5,1.2071
-0.2071,.5
;________
chk
;__3dpline__
move
all

0,0
1,0
;________
3dpoly
0,0,.1
0.5,0,1
1,0,.3

pedit
l
s

3dpoly
1,0,.3
1,.5,-.2
1,1,.5

pedit
l
s

3dpoly
1,1,.5
.5,1,-.3
0,1,1

pedit
l
s

3dpoly
0,1,1
0,.5,0.4
0,0,.1

pedit
l
s

;________
zoom
extents
;________
edgesurf
.5,0
1,.5
.5,1
0,.5
;________
chk
;________
vpoint
-.8,-1,1
;________
dxfout output_dxf\edgesurf_options.dxf
6
quit
y
