logfilename log\entget_app.log
logfileon
;_______________
(regapp "A")
(setq lin '((0 . "LINE") (5 . "36") (67 . 0) (8 . "0") (62 . 256) (6 . "BYLAYER") (370 . -1) (48 . 1.00000) (60 . 0) (39 . 0.000000) (10 1.04165 1.22034 0.000000) (11 4.24503 6.01017 0.000000) (210 0.000000 0.000000 1.00000) (-3 ("A" (1000 . "String")))))
;(setq pt1 (list 1.0 1.0 1.0))
;(setq pt1 (append '(10) pt1))
;(setq pt2 (list 2.0 2.0 2.0))
;(setq pt2 (append '(11) pt2))
;(setq lin '((0 . "LINE") (5 . "36") (67 . 0) (8 . "0") (62 . 256) (6 . "BYLAYER") (370 . -1) (48 . 1.00000) (60 . 0) (39 . 0.000000) pt1 pt2 (210 0.000000 0.000000 1.00000) (-3 ("A" (1000 . "String")))))
(entmake lin)
(entget (entlast) '("*"))
(defun addxdata (appname val) 

)
;___________
dxfout output_dxf\entget_app.dxf
6
quit
y
