logfilename log\join_options.log
logfileon
;________
(defun c:checkjoin() (setq en nil) (setq en (entget (Car (entsel)))) (if (/= en nil) (princ "OK") (alert "break did not work correctly")))
;________1
line
0,0
3,0

;________
zoom
extents
;________
break
1.4,0
1.6,0
;________
join
1.4,0
1.6,0

checkjoin
1.5,0
;________
erase
all

;________2
circle
1,1
1
;________
zoom
extents
;________
break
1.7071,0.2929
1.7071,1.7071

0.2929,1.7071
0.2929,0.2929
;________
join
1.7071,0.2929
1.7071,1.7071

checkjoin
1,2
;________
erase
all

;________3
line
0,0
3,0

;________
zoom
extents
;________
break
2,0
f
1.4,0
1.6,0
;________
join
1.4,0
1.6,0

checkjoin
1.5,0
;________
erase
all

;_________
dxfout output_dxf\join_options.dxf
6
quit
y
